In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import pickle
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
!python -m pip install wordcloud

In [2]:
from sklearn.metrics import accuracy_score,classification_report
# from wordcloud import WordCloud

In [3]:
from nltk.tokenize import word_tokenize

In [4]:
from nltk.corpus import stopwords

In [5]:
stp=stopwords.words('english')

In [6]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [7]:
from nltk.stem import SnowballStemmer
ss=SnowballStemmer("english")

In [8]:
df=pd.read_csv('Datasets/spamSMSKaggle.csv',usecols=['v1','v2'])
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.columns=['LABEL','MESSAGE']

In [10]:
df.head()

LABEL                                            MESSAGE
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df.shape

(5572, 2)

In [12]:
df['length']=df['MESSAGE'].apply(len)

In [13]:
def cleaning(strr):
    txt=re.sub('[^a-zA-Z]',' ',strr)
    txt=txt.lower()
    txt=txt.split()
    words=[ss.stem(word) for word in txt if word not in stp]
    return " ".join(words)

In [14]:
df['MESSAGE']=df['MESSAGE'].apply(cleaning)

In [15]:
df.head()

LABEL                                            MESSAGE  length
0   ham  go jurong point crazi avail bugi n great world...     111
1   ham                              ok lar joke wif u oni      29
2  spam  free entri wkli comp win fa cup final tkts st ...     155
3   ham                u dun say earli hor u c alreadi say      49
4   ham               nah think goe usf live around though      61

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv=CountVectorizer()

In [18]:
x=cv.fit(df['MESSAGE'])

In [19]:
x.vocabulary_

{'go': 2143,
 'jurong': 2787,
 'point': 4043,
 'crazi': 1160,
 'avail': 376,
 'bugi': 729,
 'great': 2217,
 'world': 6054,
 'la': 2891,
 'buffet': 727,
 'cine': 957,
 'got': 2180,
 'amor': 187,
 'wat': 5880,
 'ok': 3715,
 'lar': 2919,
 'joke': 2754,
 'wif': 5975,
 'oni': 3740,
 'free': 1984,
 'entri': 1656,
 'wkli': 6019,
 'comp': 1050,
 'win': 5986,
 'fa': 1772,
 'cup': 1210,
 'final': 1870,
 'tkts': 5465,
 'st': 5033,
 'may': 3232,
 'text': 5351,
 'receiv': 4343,
 'question': 4263,
 'std': 5061,
 'txt': 5622,
 'rate': 4306,
 'appli': 259,
 'dun': 1535,
 'say': 4586,
 'earli': 1552,
 'hor': 2442,
 'alreadi': 161,
 'nah': 3491,
 'think': 5397,
 'goe': 2147,
 'usf': 5737,
 'live': 3029,
 'around': 299,
 'though': 5414,
 'freemsg': 1990,
 'hey': 2375,
 'darl': 1257,
 'week': 5913,
 'word': 6048,
 'back': 411,
 'like': 3001,
 'fun': 2033,
 'still': 5082,
 'tb': 5296,
 'xxx': 6121,
 'chgs': 915,
 'send': 4654,
 'rcv': 4317,
 'even': 1705,
 'brother': 703,
 'speak': 4967,
 'treat': 5566,
 '

In [20]:
x.get_feature_names()

['aa',
 'aah',
 'aaniy',
 'aaooooright',
 'aathi',
 'ab',
 'abbey',
 'abdomen',
 'abeg',
 'abel',
 'aberdeen',
 'abi',
 'abil',
 'abiola',
 'abj',
 'abl',
 'abnorm',
 'abouta',
 'abroad',
 'absenc',
 'absolut',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'abus',
 'ac',
 'academ',
 'acc',
 'accent',
 'accentur',
 'accept',
 'access',
 'accid',
 'accident',
 'accommod',
 'accommodationvouch',
 'accomod',
 'accord',
 'accordin',
 'account',
 'accumul',
 'ach',
 'achan',
 'achiev',
 'acid',
 'acknowledg',
 'acl',
 'acnt',
 'aco',
 'across',
 'act',
 'actin',
 'action',
 'activ',
 'actor',
 'actual',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'addi',
 'addict',
 'address',
 'adewal',
 'adi',
 'adjust',
 'admin',
 'administr',
 'admir',
 'admiss',
 'admit',
 'ador',
 'adp',
 'adress',
 'adrian',
 'adsens',
 'adult',
 'advanc',
 'adventur',
 'advic',
 'advis',
 'advisor',
 'ae',
 'aeronaut',
 'aeroplan',
 'afew',
 'affair',
 'affect',
 'affection',
 'affidavit',
 'afford',
 'afghanistan',
 'afraid',


In [21]:
x=cv.fit_transform(df['MESSAGE']).toarray()

In [22]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
df_array=pd.DataFrame(x,columns=cv.get_feature_names())
df_array.head()

aa  aah  aaniy  aaooooright  aathi  ab  abbey  abdomen  abeg  abel  ...  \
0   0    0      0            0      0   0      0        0     0     0  ...   
1   0    0      0            0      0   0      0        0     0     0  ...   
2   0    0      0            0      0   0      0        0     0     0  ...   
3   0    0      0            0      0   0      0        0     0     0  ...   
4   0    0      0            0      0   0      0        0     0     0  ...   

   zero  zf  zhong  zindgi  zoe  zogtorius  zoom  zouk  zs  zyada  
0     0   0      0       0    0          0     0     0   0      0  
1     0   0      0       0    0          0     0     0   0      0  
2     0   0      0       0    0          0     0     0   0      0  
3     0   0      0       0    0          0     0     0   0      0  
4     0   0      0       0    0          0     0     0   0      0  

[5 rows x 6216 columns]

In [26]:
df['LABEL']=df['LABEL'].map({'ham':1,'spam':0})

In [45]:
y=pd.DataFrame(df['LABEL'])
y

LABEL
0         1
1         1
2         0
3         1
4         1
...     ...
5567      0
5568      1
5569      1
5570      1
5571      1

[5572 rows x 1 columns]

In [28]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test=train_test_split(df_array,y,test_size=0.2,random_state=0)

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [47]:
mod=MultinomialNB().fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [48]:
y_pred=mod.predict(x_test)

In [49]:
accuracy_score(y_test,y_pred)

0.9802690582959641

In [50]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [51]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.96      0.94       166
           1       0.99      0.98      0.99       949

    accuracy                           0.98      1115
   macro avg       0.95      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [52]:
pickle.dump(cv,open('transform.pkl','wb'))

In [53]:
filename='model.pkl'

In [54]:
pickle.dump(mod,open(filename,'wb'))

### testing

In [55]:
model_pickle = pickle.load(open(filename, 'rb'))
countvect=pickle.load(open('transform.pkl','rb'))

In [63]:
msg2=["hey please share your otp"]

In [64]:
vectors = countvect.transform(msg2).toarray()
model_pickle.predict(vectors)

array([1], dtype=int64)